# Generated by Django 5.2.3 on 2025-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=100)),
                ('seat_number', models.TextField()),
                ('select_date', models.DateField()),
                ('select_time', models.TimeField()),
            ],
        ),
    ]
