# Generated by Django 5.2.3 on 2025-07-12 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbook',
            name='user',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketbook',
            name='bus_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary Bus'), ('ac', 'AC Bus'), ('sleeper', 'Sleeper Coach')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketbook',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
