# Generated by Django 5.2.3 on 2025-07-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ticketbook_user_alter_ticketbook_bus_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbook',
            name='ticket_amount',
            field=models.CharField(default='ticket_amount', max_length=20),
            preserve_default=False,
        ),
    ]
