# Generated by Django 5.2.3 on 2025-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trippackage_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippackage',
            name='cust_name',
            field=models.CharField(default='mahesh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trippackage',
            name='places',
            field=models.JSONField(default='banglore'),
            preserve_default=False,
        ),
    ]
