# Generated by Django 5.2.3 on 2025-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_trippackage_cust_name_trippackage_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippackage',
            name='no_of_tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
